using System;
using System.Reflection;
using System.Runtime.CompilerServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(false)]
[assembly: AssemblyTitleAttribute("ElfFileReader for Microsoft .NET Framework 2.0")]
[assembly: AssemblyDescriptionAttribute(" Cisco Incident Response - ElfFileReader AnalysisPlugin")]
[assembly: AssemblyCompanyAttribute("Recurity Labs GmbH")]
[assembly: AssemblyProductAttribute("CIR ElfFileReader AnalysisPlugin")]
[assembly: AssemblyCopyrightAttribute("Recurity-Labs GmbH All rights reserved.")]
[assembly: AssemblyVersionAttribute("1.0.0.0")]
[assembly: AssemblyInformationalVersionAttribute("1.0.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.0.0")]

